#!/usr/bin/env bash
# Deploy a perc5ive .fbin artifact to a Solana cluster via `five deploy`.
#
# Usage:
#   scripts/deploy.sh <artifact_name> [--target <devnet|testnet|mainnet|local>] [--dry-run]
#
# `<artifact_name>` is one of: perc5ive, sov, pyth_race, lp_perp.
# The corresponding `target/<name>.fbin` (regenerated by `cargo build`) is
# copied to `target/<name>.bin` so the @five-vm/cli accepts it (the CLI
# whitelists .five/.bin/.v extensions only) and then handed to `five deploy`.
#
# Defaults to the cluster set in `solana config get` if --target is omitted.

set -euo pipefail

ARTIFACT="${1:-}"
shift || true

if [[ -z "${ARTIFACT}" ]]; then
    echo "usage: scripts/deploy.sh <perc5ive|sov|pyth_race|lp_perp> [five deploy flags...]" >&2
    exit 2
fi

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${REPO_ROOT}/target/${ARTIFACT}.fbin"
SHIPPED="${REPO_ROOT}/target/${ARTIFACT}.bin"

if [[ ! -f "${SOURCE}" ]]; then
    echo "missing ${SOURCE} — run \`cargo build\` first to regenerate it" >&2
    exit 1
fi

cp "${SOURCE}" "${SHIPPED}"
echo "→ deploying ${ARTIFACT} ($(wc -c <"${SHIPPED}") bytes)"
exec five deploy "${SHIPPED}" "$@"
